# Generated by Django 6.0.3 on 2026-04-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_tags_image_category_softdelete'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='activities__is_dele_ef1836_idx',
            old_name='act_del_end_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='activities__categor_036116_idx',
            old_name='act_category_idx',
        ),
    ]
